# Generated by Django 5.2.6 on 2025-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_task_completed_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
